### PR TITLE
update to 3.3.2

### PR DESCRIPTION
**Pull request by GabMus**

### CODE REVIEW

**Comment by GabMus** [comment]
!build

**Comment by GabMus** [comment]
bot, build

**Comment by alnadev** [comment]
```
{
    "errors": [
        "finish-args-unnecessary-appid-own-name",
        "finish-args-arbitrary-autostart-access"
    ]
}
```

The Errors above are caused by these Three Properties, which are detected by the linter:

- Line 16 | "--filesystem=xdg-config/autostart", | caused "finish-args-arbitrary-autostart-access" 
- Line 25 | "--own-name=org.gabmus.hydrapaper", | caused "finish-args-unnecessary-appid-own-name"
- Line 26 | "--own-name=org.gabmus.hydrapaper.Daemon" | caused "finish-args-unnecessary-appid-own-name"

In a Separate pull request #8, I Tried to remove them and the building process completed successfully, and the program worked perfectly as expected.

@GabMus You may have to remove these lines then rebuild again.

**Comment by GabMus** [comment]
thanks, will take a look

**Comment by GabMus** [comment]
!buildbot, build

**Comment by GabMus** [comment]
bot, build

**Comment by GabMus** [comment]
bot, build

**Pull request closed without merging**
